aircraft=aircraft
alumni=alumnus
analyses=analysis
antennae=antenna
appendices=appendix
axes=axis
bacteria=bacterium
barracks=barracks
bases=basis
bison=bison
cacti=cactus
calves=calf
children=child
cod=cod
corpora=corpus
corps=corps
covenants=covenant
criteria=criterion
curricula=curriculum
data=datum
deer=deer
diagnoses=diagnosis
dice=die
elves=elf
feet=foot
fish=fish
formulae=formula
fungi=fungus
geese=goose
genera=genus
halves=half
hypotheses=hypothesis
indexes=index
indices=index
knives=knife
larvae=larva
leaves=leaf
lice=louse
lives=life
loaves=loaf
matrices=matrix
means=mean
media=medium
memoranda=memorandum
men=man
mice=mouse
moose=moose
nebulae=nebula
nuclei=nucleus
oases=oasis
offspring=offspring
oxen=ox
parentheses=parenthesis
people=person
phenomena=phenomenon
pike=pike
pliers=pliers
radii=radius
salmon=salmon
scarves=scarf
scissors=scissors
series=series
sheep=sheep
shelves=shelf
shrimp=shrimp
species=species
squid=squid
stimuli=stimulus
strata=stratum
swine=swine
syllabi=syllabus
symposia=symposium
synopses=synopsis
teeth=tooth
theses=thesis
thieves=thief
tongs=tongs
trout=trout
vertebrae=vertebra
vertices=vertex
vortices=vortex
wives=wife
wolves=wolf
women=woman